### ISSUE TITLE
Difficulty getting a sandbox

### ISSUE THREAD

**Issue by alanef** [danielbachhuber/gutenberg-plugin-compatibility#10]
WP Sandbox or Cloudflare is struggling to launch test sand boxes

> Please try again in a few minutes.</p> </div> </div> </div> <div class="cf-error-footer cf-wrapper"> <p> <span class="cf-footer-item">Cloudflare Ray ID: <strong>3f75cedb1bb906e8

**Comment by alanef** [comment]
fyi the time out is at 60 seconds

**Comment by danielbachhuber** [comment]
@alanef Did this resolve itself?

**Comment by joeguilmette** [comment]
We were having some performance issues on Sandbox but they were resolved around 7hrs ago.

**Comment by danielbachhuber** [comment]
👍 Thanks @joeguilmette

**Comment by alanef** [comment]
Timeout are back :(

**Comment by joeguilmette** [comment]
Had another issue, resolved around 12hrs ago.
