### ISSUE TITLE
Actuality of the test results?

### ISSUE THREAD

**Issue by La-Geek** [danielbachhuber/gutenberg-plugin-compatibility#12]
This is a great project! Thank you for your countless efforts to increase Gutenberg's compatibility @danielbachhuber.

One question: How do you ensure that the test results are up to date?

**Comment by danielbachhuber** [comment]
Hey @La-Geek,

Thanks for the question. The initial focus for the project is to generate a complete data set for research purposes. The "Create New Test Environment" currently only creates environments for plugins where `is_compatible=unknown`.

If this research goes well, we'll eventually report compatibility results to individual site owners and make sure the test results are up to date when we do so. We have a good amount of work between now and then, however.
