### ISSUE TITLE
Facing the issue (Invalid token provided. Please reauthenticate.) while I clicked on Create New Test Environment button

### ISSUE THREAD

**Issue by abdullah1908** [danielbachhuber/gutenberg-plugin-compatibility#14]
Hi,

I am facing the issue while I clicked on **Create New Test Environment** button. Can you please let me know either it is an issue or any type of specific warning. I have also attached a screenshot. Please have a look.
![gutenber plugin compatibilty testing](https://user-images.githubusercontent.com/14175927/37849283-e807c46c-2ef8-11e8-8839-c7ee21bd5f68.png)

Thanks & Regards,
Abdullah

**Comment by alanef** [comment]
I'm having the same issue

**Comment by alanef** [comment]
btw running in incognito mode works for me, so must be a cookie stored somewhere that hasn't been reset on re-login in

**Comment by danielbachhuber** [comment]
@abdullah1908 Can you try resetting the cookies in your browser?

**Comment by jonathanbossenger** [comment]
@abdullah1908 I can confirm that clearing the cookie for plugincompat.danielbachhuber.com resolves the isssue.

**Comment by mnelson4** [comment]
I also got that issue, and resetting cookies fixed it (although when I first used a Firefox add-on to only reset plugincompat.danielbachhuber.com 's cookies, it didn't fix it)

**Comment by abdullah1908** [comment]
Sorry for the delayed response. It works for me after resetting cookies :-)
