### ISSUE TITLE
Custom Post type plugins

### ISSUE THREAD

**Issue by bph** [danielbachhuber/gutenberg-plugin-compatibility#15]
Example: popup-builder
It works with the current version of Gutenberg as it only touches post and page post types. 

It's hard to predict what'll happened when Gutenberg gets into Core and becomes the default editor. But I assume this popup-builder plugin will have some incompatibility issues. 

Which brings me to the question:
test environment is gutenberg plugin. Should I set compatibility to 'Yes" or leaving to likely_no"

**Comment by danielbachhuber** [comment]
I'd suggest this is "yes", it's compatible.

Generally, I'd suggest following the definition very literally:

> A WordPress user can perform the same functional task with Gutenberg active. For instance, if the plugin includes an "Add Media" button, it's considered Gutenberg-compatible when it has a block registered for the Gutenberg inserter. Feature-parity, essentially.

If the plugin works right now, then it's compatible. If it breaks at some future date, then we can mark it incompatible.

**Comment by ernilambar** [comment]
Thanks for the clarification. I was about to ask this question. I have updated compatibility to `yes` from `likely_yes` of a testimonial plugin.
