### ISSUE TITLE
Filter per reviewer

### ISSUE THREAD

**Issue by bph** [danielbachhuber/gutenberg-plugin-compatibility#16]
Just went through my first round of testing. 
Is there a way to get a list of the plugins I reviewed? 

I'd like to know: 
- How many plugins I was able to test in a single sitting 
- double-check my entries to make sure I changed the select box from "testing" to something else, and to see if my comments are still clear on second reading. (English isn't my native language)
- If I made an impact  to reduce the "Unknown"  portion in the pie chart. 
- Don't really care about other testers numbers but it would be nice to have it anonymized for benchmarking my own progress

**Comment by danielbachhuber** [comment]
> Is there a way to get a list of the plugins I reviewed?

With this Knack-based system, unfortunately no. There's a revisions system, so you can see the changes to the plugins, but no way of programmatically querying the system.

> I'd like to know:

I agree, these stats could be useful to have.

**Comment by bph** [comment]
It was a fun project. Thanks Daniel. Closing this issue during annual purge. 💯
