### ISSUE TITLE
Display review date on Details page.

### ISSUE THREAD

**Issue by bph** [danielbachhuber/gutenberg-plugin-compatibility#19]
For some plugins I notice that there might be an update between the review and the last update of the plugin. 
[Example: all-in-one-seo  ](https://plugincompat.danielbachhuber.com/#compatibility-results/view-plugin-details/5a95f3dd4915723fa0b27d71/)

Seems to have fixed the issue: 
https://github.com/WordPress/gutenberg/issues/3959

For now I added the discussion link, but didn't reset the compatibility as I wasn't able to create a test environment for it, to verify.
 
It would be helpful to have a date on the plugin review on the details page. 

Then with help of discussion link + "last updated" of the plugin, a viewer could see that there was further development and do their own testing.  

Also maybe replace the "last updated: 2 weeks " with current version "2.5"

![screen shot 2018-04-18 at 10 06 23 am](https://user-images.githubusercontent.com/39980/38937063-4efb35e0-42f0-11e8-936e-c6267325a677.png)

**Comment by danielbachhuber** [comment]
👋 @bph, thanks for the feedback!

I agree with the improvements you suggest. However, Knack (the tool I used to built the database) is somewhat limited in terms of how much we can customize it.

At this point, if we continue to invest time into the compatibility database, I'm leaning more towards replicating it on WordPress.org. I'll have a better since of its direction in the next week.

**Comment by bph** [comment]
You are welcome.  @danielbachhuber 
_... waiting patiently ..._

**Comment by bph** [comment]
@danielbachhuber do you have data regarding review date and who reviewed it in the db? Or is the data available via the export all the data you actually have from this project?

**Comment by danielbachhuber** [comment]
> do you have data regarding review date and who reviewed it in the db?

I do, but only through the web UI (because of a Knack limitation). It's not available in the export.

**Comment by bph** [comment]
Great project. Thanks for you hard work. Closing this issue during annual purge of 2019 👍
