### ISSUE TITLE
What are our requirements for meta-boxes with additional settings?

### ISSUE THREAD

**Issue by glebkema** [danielbachhuber/gutenberg-plugin-compatibility#23]
"[Top 10 – Popular posts plugin for WordPress](https://wordpress.org/plugins/top-10/)"

This plugin adds a meta-box for the popularity settings of the post, which is displayed in Gutenberg in the same way as in the classic editor.

![top10-classic](https://user-images.githubusercontent.com/3881568/39766239-7e5479b2-52ec-11e8-88d1-36182e75ac88.png)

![top10-gutenberg](https://user-images.githubusercontent.com/3881568/39766242-7e92459e-52ec-11e8-92ff-40a744a6eeb4.png)

I'm not sure if the author should include this meta-box in the Gutenberg settings panel. So for now, I chose `likely yes` and `Existing functions work in Gutenberg`, and [wrote a detailed comment](https://plugincompat.danielbachhuber.com/#compatibility-results/view-plugin-details/5a95f3e74915723fa0b2834c/).

What is our position about the meta-boxes with additional settings?

**Comment by danielbachhuber** [comment]
@glebkema I think your assessment is great! There's nothing I'd change.

If the meta box appears correctly in Gutenberg, and works as expected, then I think it's compatible with Gutenberg.
