### ISSUE TITLE
EWWW Image Optimizer compatibility

### ISSUE THREAD

**Issue by nosilver4u** [danielbachhuber/gutenberg-plugin-compatibility#26]
With the latest release of EWWW IO, we have ensured that all our plugins are Gutenberg compatible.
The main plugin (slug ewww-image-optimizer) simply needs the reason changed to "Existing functionality works in Gutenberg". The cloud version (ewww-image-optimizer-cloud) needs to be updated to "yes" and the same reason.
I checked Imsanity, and it is already marked appropriately at this point.
Thanks!

**Comment by danielbachhuber** [comment]
Hi @nosilver4u,

Thanks for the update. The plugin compatibility database was originally meant as a research project, not a canonical database of compatibility. I've removed the interactive database from the homepage and updated it accordingly.
