### ISSUE TITLE
The entry takes a long time to visualize

### ISSUE THREAD

**Issue by johnele** [danielbachhuber/gutenberg-plugin-compatibility#27]
Hi, I would like to make a query and it is that when viewing or saving an entry in Gutenberg this is stuck and does not load ... I must update the page to make changes, do you know what this detail should be? the template that I occupy is MH Magazine 3.8.2

**Comment by danielbachhuber** [comment]
Hi @johnele,

This GitHub repository isn't meant for general support. I'd suggest posting your question to the WordPress.org [support forums](https://wordpress.org/support/). Thanks
