### ISSUE TITLE
Problem developing an add-in that adds buttons on the toolbar

### ISSUE THREAD

**Issue by ghost** [danielbachhuber/gutenberg-plugin-compatibility#28]
Hello everyone!
I work for a company that works with Wordpress and I am in charge of developing a plugin that makes writing faster.
The problem is that with the previous version of the classic editor, a plugin responsible for add buttons was developed in the toolbar. And now with gutenberg this has been uninhabited. Is it possible to add these buttons on the toolbar?

**Comment by JuanGarciaGutierrez** [comment]
> Hello everyone!
> I work for a company that works with Wordpress and I am in charge of developing a plugin that makes writing faster.
> The problem is that with the previous version of the classic editor, a plugin responsible for add buttons was developed in the toolbar. And now with gutenberg this has been uninhabited. Is it possible to add these buttons on the toolbar?
